/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpelareRouteImport } from './routes/spelare'
import { Route as SchemaRouteImport } from './routes/schema'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndexIndexRouteImport } from './routes/index.index'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as TvHomeAwayRouteImport } from './routes/tv.$home.$away'
import { Route as AuthenticatedAdminVmixRouteImport } from './routes/_authenticated/admin.vmix'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminLogosRouteImport } from './routes/_authenticated/admin.logos'
import { Route as AuthenticatedAdminHealthRouteImport } from './routes/_authenticated/admin.health'
import { Route as AuthenticatedAdminAssetsRouteImport } from './routes/_authenticated/admin.assets'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicVmixStandingsRouteImport } from './routes/api/public/vmix/standings'
import { Route as ApiPublicVmixCurrentRouteImport } from './routes/api/public/vmix/current'
import { Route as ApiPublicHooksPregameEmailsRouteImport } from './routes/api/public/hooks/pregame-emails'
import { Route as ApiPublicHooksPostgameEmailsRouteImport } from './routes/api/public/hooks/postgame-emails'
import { Route as ApiPublicVmixLineupVersionRouteImport } from './routes/api/public/vmix/lineup.$version'

const SpelareRoute = SpelareRouteImport.update({
  id: '/spelare',
  path: '/spelare',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexIndexRoute = IndexIndexRouteImport.update({
  id: '/index/',
  path: '/index/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const TvHomeAwayRoute = TvHomeAwayRouteImport.update({
  id: '/tv/$home/$away',
  path: '/tv/$home/$away',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminVmixRoute = AuthenticatedAdminVmixRouteImport.update({
  id: '/admin/vmix',
  path: '/admin/vmix',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLogosRoute = AuthenticatedAdminLogosRouteImport.update({
  id: '/admin/logos',
  path: '/admin/logos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminHealthRoute =
  AuthenticatedAdminHealthRouteImport.update({
    id: '/admin/health',
    path: '/admin/health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAssetsRoute =
  AuthenticatedAdminAssetsRouteImport.update({
    id: '/admin/assets',
    path: '/admin/assets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVmixStandingsRoute = ApiPublicVmixStandingsRouteImport.update({
  id: '/api/public/vmix/standings',
  path: '/api/public/vmix/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVmixCurrentRoute = ApiPublicVmixCurrentRouteImport.update({
  id: '/api/public/vmix/current',
  path: '/api/public/vmix/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPregameEmailsRoute =
  ApiPublicHooksPregameEmailsRouteImport.update({
    id: '/api/public/hooks/pregame-emails',
    path: '/api/public/hooks/pregame-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPostgameEmailsRoute =
  ApiPublicHooksPostgameEmailsRouteImport.update({
    id: '/api/public/hooks/postgame-emails',
    path: '/api/public/hooks/postgame-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVmixLineupVersionRoute =
  ApiPublicVmixLineupVersionRouteImport.update({
    id: '/api/public/vmix/lineup/$version',
    path: '/api/public/vmix/lineup/$version',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schema': typeof SchemaRoute
  '/spelare': typeof SpelareRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/index/': typeof IndexIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/logos': typeof AuthenticatedAdminLogosRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vmix': typeof AuthenticatedAdminVmixRoute
  '/tv/$home/$away': typeof TvHomeAwayRoute
  '/api/public/hooks/postgame-emails': typeof ApiPublicHooksPostgameEmailsRoute
  '/api/public/hooks/pregame-emails': typeof ApiPublicHooksPregameEmailsRoute
  '/api/public/vmix/current': typeof ApiPublicVmixCurrentRoute
  '/api/public/vmix/standings': typeof ApiPublicVmixStandingsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/vmix/lineup/$version': typeof ApiPublicVmixLineupVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schema': typeof SchemaRoute
  '/spelare': typeof SpelareRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/index': typeof IndexIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/logos': typeof AuthenticatedAdminLogosRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vmix': typeof AuthenticatedAdminVmixRoute
  '/tv/$home/$away': typeof TvHomeAwayRoute
  '/api/public/hooks/postgame-emails': typeof ApiPublicHooksPostgameEmailsRoute
  '/api/public/hooks/pregame-emails': typeof ApiPublicHooksPregameEmailsRoute
  '/api/public/vmix/current': typeof ApiPublicVmixCurrentRoute
  '/api/public/vmix/standings': typeof ApiPublicVmixStandingsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/vmix/lineup/$version': typeof ApiPublicVmixLineupVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schema': typeof SchemaRoute
  '/spelare': typeof SpelareRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/index/': typeof IndexIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/_authenticated/admin/health': typeof AuthenticatedAdminHealthRoute
  '/_authenticated/admin/logos': typeof AuthenticatedAdminLogosRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/vmix': typeof AuthenticatedAdminVmixRoute
  '/tv/$home/$away': typeof TvHomeAwayRoute
  '/api/public/hooks/postgame-emails': typeof ApiPublicHooksPostgameEmailsRoute
  '/api/public/hooks/pregame-emails': typeof ApiPublicHooksPregameEmailsRoute
  '/api/public/vmix/current': typeof ApiPublicVmixCurrentRoute
  '/api/public/vmix/standings': typeof ApiPublicVmixStandingsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/vmix/lineup/$version': typeof ApiPublicVmixLineupVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compare'
    | '/mcp'
    | '/reset-password'
    | '/schema'
    | '/spelare'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/notifications'
    | '/index/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/assets'
    | '/admin/health'
    | '/admin/logos'
    | '/admin/logs'
    | '/admin/users'
    | '/admin/vmix'
    | '/tv/$home/$away'
    | '/api/public/hooks/postgame-emails'
    | '/api/public/hooks/pregame-emails'
    | '/api/public/vmix/current'
    | '/api/public/vmix/standings'
    | '/lovable/email/queue/process'
    | '/api/public/vmix/lineup/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compare'
    | '/mcp'
    | '/reset-password'
    | '/schema'
    | '/spelare'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/notifications'
    | '/index'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/assets'
    | '/admin/health'
    | '/admin/logos'
    | '/admin/logs'
    | '/admin/users'
    | '/admin/vmix'
    | '/tv/$home/$away'
    | '/api/public/hooks/postgame-emails'
    | '/api/public/hooks/pregame-emails'
    | '/api/public/vmix/current'
    | '/api/public/vmix/standings'
    | '/lovable/email/queue/process'
    | '/api/public/vmix/lineup/$version'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/compare'
    | '/mcp'
    | '/reset-password'
    | '/schema'
    | '/spelare'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/notifications'
    | '/index/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/assets'
    | '/_authenticated/admin/health'
    | '/_authenticated/admin/logos'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/vmix'
    | '/tv/$home/$away'
    | '/api/public/hooks/postgame-emails'
    | '/api/public/hooks/pregame-emails'
    | '/api/public/vmix/current'
    | '/api/public/vmix/standings'
    | '/lovable/email/queue/process'
    | '/api/public/vmix/lineup/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchemaRoute: typeof SchemaRoute
  SpelareRoute: typeof SpelareRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  IndexIndexRoute: typeof IndexIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  TvHomeAwayRoute: typeof TvHomeAwayRoute
  ApiPublicHooksPostgameEmailsRoute: typeof ApiPublicHooksPostgameEmailsRoute
  ApiPublicHooksPregameEmailsRoute: typeof ApiPublicHooksPregameEmailsRoute
  ApiPublicVmixCurrentRoute: typeof ApiPublicVmixCurrentRoute
  ApiPublicVmixStandingsRoute: typeof ApiPublicVmixStandingsRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiPublicVmixLineupVersionRoute: typeof ApiPublicVmixLineupVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spelare': {
      id: '/spelare'
      path: '/spelare'
      fullPath: '/spelare'
      preLoaderRoute: typeof SpelareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/': {
      id: '/index/'
      path: '/index'
      fullPath: '/index/'
      preLoaderRoute: typeof IndexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$home/$away': {
      id: '/tv/$home/$away'
      path: '/tv/$home/$away'
      fullPath: '/tv/$home/$away'
      preLoaderRoute: typeof TvHomeAwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/vmix': {
      id: '/_authenticated/admin/vmix'
      path: '/admin/vmix'
      fullPath: '/admin/vmix'
      preLoaderRoute: typeof AuthenticatedAdminVmixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/logos': {
      id: '/_authenticated/admin/logos'
      path: '/admin/logos'
      fullPath: '/admin/logos'
      preLoaderRoute: typeof AuthenticatedAdminLogosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/health': {
      id: '/_authenticated/admin/health'
      path: '/admin/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AuthenticatedAdminHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/assets': {
      id: '/_authenticated/admin/assets'
      path: '/admin/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AuthenticatedAdminAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vmix/standings': {
      id: '/api/public/vmix/standings'
      path: '/api/public/vmix/standings'
      fullPath: '/api/public/vmix/standings'
      preLoaderRoute: typeof ApiPublicVmixStandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vmix/current': {
      id: '/api/public/vmix/current'
      path: '/api/public/vmix/current'
      fullPath: '/api/public/vmix/current'
      preLoaderRoute: typeof ApiPublicVmixCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pregame-emails': {
      id: '/api/public/hooks/pregame-emails'
      path: '/api/public/hooks/pregame-emails'
      fullPath: '/api/public/hooks/pregame-emails'
      preLoaderRoute: typeof ApiPublicHooksPregameEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/postgame-emails': {
      id: '/api/public/hooks/postgame-emails'
      path: '/api/public/hooks/postgame-emails'
      fullPath: '/api/public/hooks/postgame-emails'
      preLoaderRoute: typeof ApiPublicHooksPostgameEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vmix/lineup/$version': {
      id: '/api/public/vmix/lineup/$version'
      path: '/api/public/vmix/lineup/$version'
      fullPath: '/api/public/vmix/lineup/$version'
      preLoaderRoute: typeof ApiPublicVmixLineupVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedAdminAssetsRoute: typeof AuthenticatedAdminAssetsRoute
  AuthenticatedAdminHealthRoute: typeof AuthenticatedAdminHealthRoute
  AuthenticatedAdminLogosRoute: typeof AuthenticatedAdminLogosRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVmixRoute: typeof AuthenticatedAdminVmixRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedAdminAssetsRoute: AuthenticatedAdminAssetsRoute,
  AuthenticatedAdminHealthRoute: AuthenticatedAdminHealthRoute,
  AuthenticatedAdminLogosRoute: AuthenticatedAdminLogosRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVmixRoute: AuthenticatedAdminVmixRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchemaRoute: SchemaRoute,
  SpelareRoute: SpelareRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  IndexIndexRoute: IndexIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  TvHomeAwayRoute: TvHomeAwayRoute,
  ApiPublicHooksPostgameEmailsRoute: ApiPublicHooksPostgameEmailsRoute,
  ApiPublicHooksPregameEmailsRoute: ApiPublicHooksPregameEmailsRoute,
  ApiPublicVmixCurrentRoute: ApiPublicVmixCurrentRoute,
  ApiPublicVmixStandingsRoute: ApiPublicVmixStandingsRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiPublicVmixLineupVersionRoute: ApiPublicVmixLineupVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
